config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#show'

  get '/auth/instagram', as: :login
  get 'auth/instagram/callback', to: 'sessions#create'
  delete '/logout', as: :logout, to: 'sessions#destroy'

  mount Attachinary::Engine => "/attachinary"

  resources :pictures
  resources :inspirations, only: [:show, :index]
  resources :users

end

app/models/inspiration.rb
class Inspiration < ActiveRecord::Base
  before_save :set_slug
  validates :name, presence: true
  validates :title, presence: true
  validates :slug, presence: true

  def set_slug
    if slug.nil? || slug == ""
      self.slug = name.parameterize
    else
      self.slug = slug.parameterize
    end
  end

  def to_param
    slug
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pictures
  has_attachments :photos

  def self.find_or_create_from_auth(oauth)
    user = User.find_or_create_by(provider: oauth.provider, uid: oauth.uid)
    user.nickname = oauth.info.nickname
    user.name = oauth.info.full_name
    user.image = oauth.info.image
    user.website = oauth.info.website
    user.token = oauth.credentials.token
    user.save
    user
  end

  def client
    @instagram_client ||= Instagram.client(access_token: token)
  end

  def media
    client.user_media_feed
  end

  def user
    client.user
  end

  def recent_media
    client.user_recent_media
  end

  def feed(category)
    client.tag_recent_media(category, options = {:count => 50})
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:destroy]

  def create
    current_user.pictures.create(picture_params)
    redirect_to user_path(current_user)
  end

  def destroy
    @picture.destroy
    redirect_to user_path(current_user)
  end

  private

  def picture_params
    params.permit(:image_url)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @pictures = current_user.pictures
  end

  def destroy
    redirect_to user_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babyshower_helper.rb
module BabyshowerHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/create_account_helper.rb
module CreateAccountHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/inspiration_helper.rb
module InspirationHelper
end

app/helpers/kidsdecor_helper.rb
module KidsdecorHelper
end

app/helpers/kidsfashion_helper.rb
module KidsfashionHelper
end

app/helpers/kidsfood_helper.rb
module KidsfoodHelper
end

app/helpers/kidsfurniture_helper.rb
module KidsfurnitureHelper
end

app/helpers/kidsofinstagram_helper.rb
module KidsofinstagramHelper
end

app/helpers/kidsparty_helper.rb
module KidspartyHelper
end

app/helpers/kidsrooms_helper.rb
module KidsroomsHelper
end

app/helpers/picture_helper.rb
module PictureHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/new.html.erb
<div class="col-md-2"></div>
<div class="create_account col-md-8">
  <p>Download the Instagram app for iOS from the App Store
    Android from Google Play Store or Windows Phone from the Windows Phone Store.
    Once the app is installed, tap to open it.
    Tap Sign Up, then enter your email address and tap Next OR
    tap Log In with Facebook to sign up with your Facebook account.</p>
</div>
<div class="col-md-2"></div>

app/views/users/show.html.erb
<div class="row top">

<div class="col-md-12 pic"><%= image_tag current_user.image, class: "img-circle", size: "200x200"%></div>
  <div class="name col-md-12"><%= current_user.nickname %>
    <h4>>>>>><<<<<</h4>
</div>


<div class="bio col-md-12">
  <span><h3><%= current_user.user.full_name %></h3> <%= current_user.user.bio %></span><br>
</div>

<div class="col-md-4"></div>
</div>

<div class="row-border col-md-12"></div>

<div class="row">
  <div class="style-show col-md-12">
    <% @pictures.each do |pic| %>
      <%= link_to image_tag(pic.image_url, size: '400x400'), "#myModal-#{pic.id}", :data => { :toggle =>"modal", :target => "#myModal-#{pic.id}"} %>
      <div id="myModal-<%= pic.id %>" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title"><%= image_tag("i-heart-it.jpg", size: "300x200") %></h4>
            </div>
            <div class="modal-body">
              <div class="modal-style">
                <%= image_tag pic.image_url %>
                <%= link_to "x delete x", picture_path(pic), method: :delete, data: {confirm: "sure you want to delete this photo?!"} %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>