config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#show'

  get '/auth/instagram', as: :login
  get 'auth/instagram/callback', to: 'sessions#create'
  delete '/logout', as: :logout, to: 'sessions#destroy'

  mount Attachinary::Engine => "/attachinary"

  resources :pictures
  resources :inspirations, only: [:show, :index]
  resources :users

end

app/models/inspiration.rb
class Inspiration < ActiveRecord::Base
  before_save :set_slug
  validates :name, presence: true
  validates :title, presence: true
  validates :slug, presence: true

  def set_slug
    if slug.nil? || slug == ""
      self.slug = name.parameterize
    else
      self.slug = slug.parameterize
    end
  end

  def to_param
    slug
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pictures
  has_attachments :photos

  def self.find_or_create_from_auth(oauth)
    user = User.find_or_create_by(provider: oauth.provider, uid: oauth.uid)
    user.nickname = oauth.info.nickname
    user.name = oauth.info.full_name
    user.image = oauth.info.image
    user.website = oauth.info.website
    user.token = oauth.credentials.token
    user.save
    user
  end

  def client
    @instagram_client ||= Instagram.client(access_token: token)
  end

  def media
    client.user_media_feed
  end

  def user
    client.user
  end

  def recent_media
    client.user_recent_media
  end

  def feed(category)
    client.tag_recent_media(category, options = {:count => 50})
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @pictures = current_user.pictures
  end

  def destroy
    redirect_to user_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babyshower_helper.rb
module BabyshowerHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/create_account_helper.rb
module CreateAccountHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/inspiration_helper.rb
module InspirationHelper
end

app/helpers/kidsdecor_helper.rb
module KidsdecorHelper
end

app/helpers/kidsfashion_helper.rb
module KidsfashionHelper
end

app/helpers/kidsfood_helper.rb
module KidsfoodHelper
end

app/helpers/kidsfurniture_helper.rb
module KidsfurnitureHelper
end

app/helpers/kidsparty_helper.rb
module KidspartyHelper
end

app/helpers/kidsrooms_helper.rb
module KidsroomsHelper
end

app/helpers/picture_helper.rb
module PictureHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="logo col-md-3">
    <%= link_to image_tag("i-heart-it.jpg"), root_path %>
  </div>
<div class="user-path col-md-3">
  <% if current_user %>
    <%= link_to current_user.user.username, user_path(current_user) %>
  <% end %>
</div>
<div class="nav-links col-md-3">
  <% if current_user %>
    <%= link_to "Inspiration", inspirations_path %>
    <% end %>
</div>
<div class="nav-links col-md-3">
  <% if current_user %>
    <%= link_to "logout", logout_path, method: :delete %>
  <% end%>
</div>
<div class="create-account col-md-9">
  <% if !current_user %>
  <%= link_to "Create Account", new_user_path %>
  <% end %>
</div>





    <!-- <%= link_to "logout", logout_path, method: :delete %> -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>i heart it</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= cloudinary_js_config %>
  <link href='//fonts.googleapis.com/css?family=Dawning+of+a+New+Day' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Playfair+Display+SC:400,900italic,900,400italic,700,700italic' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Lato:400,100' rel='stylesheet' type='text/css'>
</head>
<body>

  <%= render partial: 'layouts/nav' %>


<div class="container">

<%= yield %>

</div>

</body>
</html>

app/views/shared/_form.html.erb
<%= form_for(Picture.new) do %>
  <%= hidden_field_tag :image_url, locals.images.standard_resolution.url %>
  <%= button_tag image_tag(locals.images.standard_resolution.url), id: "button"%>
<% end %>